#' Motor portfolio — synthesised cube
#'
#' Aggregated motor-insurance portfolio for use in the package's example
#' workflow. One row per
#' `(Year × Insurance_Company × Fleet × Vehicle_type × Cover × Age_Class ×
#' Gender)` segment, with vehicle counts and earned premium summed over the
#' segment.
#'
#' Built by `data-raw/build.R` from
#' [`insuranceData::dataCar`](https://cran.r-project.org/package=insuranceData)
#' (de Jong & Heller, 2008). The single-insurer, single-year `dataCar` is
#' replicated across `Year ∈ {2019..2024}` and partitioned across ten
#' synthetic insurers (`Company_01` … `Company_10`), each with its own
#' premium and loss multipliers so loss ratios differ across the portfolio.
#'
#' @format A data frame with 20,921 rows and 9 columns:
#' \describe{
#'   \item{Year}{integer; accident / policy year (2019–2024). Synthesised.}
#'   \item{Insurance_Company}{character; `Company_01`..`Company_10`. Synthesised.}
#'   \item{Fleet}{character; `Fleet` / `Non-Fleet`. Synthesised (~10/90 split).}
#'   \item{Vehicle_type}{character; 13 categories from `dataCar$veh_body`
#'     (`SEDAN`, `HBACK`, `STNWG`, `UTE`, …).}
#'   \item{Cover}{character; `Comprehensive` / `Third-Party`. Synthesised
#'     (~60/40 split); third-party priced ~40% lower.}
#'   \item{Age_Class}{character; `1`..`6`, from `dataCar$agecat`.}
#'   \item{Gender}{character; `F` / `M`, from `dataCar$gender`.}
#'   \item{Vehicles}{integer; count of underlying policies aggregated.}
#'   \item{Premium}{numeric; sum of segment premium ≈ exposure × veh_value
#'     × 1500 × company-multiplier × cover-adjustment.}
#' }
#'
#' @source de Jong, P. and Heller, G. (2008). *Generalized Linear Models for
#'   Insurance Data*. Cambridge University Press. Underlying data via the
#'   [insuranceData](https://cran.r-project.org/package=insuranceData)
#'   package.
#'
#' @seealso [motor_losses] for the matching loss-development cube.
#' @keywords datasets
"motor_portfolio"


#' Motor losses — synthesised loss-development cube
#'
#' Loss data at the same segmentation grain as [motor_portfolio]. One row per
#' `(Year × Insurance_Company × Fleet × Vehicle_type × Cover × Age_Class ×
#' Gender)` segment with non-zero claims. Each segment carries cumulative
#' paid amounts at sixteen development years (`DY0`..`DY15`).
#'
#' Built by `data-raw/build.R`. Total incurred per segment comes from
#' aggregated `dataCar$claimcst0` scaled by per-company loss multipliers; the
#' development pattern (`DY0`..`DY15`) is generated by spreading
#' `Total_Incurred` across sixteen development years using the average
#' paid-to-ultimate proportions of
#' [`ChainLadder::MW2014`](https://cran.r-project.org/package=ChainLadder),
#' the textbook 17×17 cumulative paid triangle from Wüthrich & Merz (2014).
#'
#' @format A data frame with 8,958 rows and 27 columns:
#' \describe{
#'   \item{Year}{integer; accident year (2019–2024).}
#'   \item{Insurance_Company}{character; `Company_01`..`Company_10`.}
#'   \item{Fleet}{character; `Fleet` / `Non-Fleet`.}
#'   \item{Vehicle_type}{character; as in [motor_portfolio].}
#'   \item{Cover}{character; as in [motor_portfolio].}
#'   \item{Age_Class}{character; as in [motor_portfolio].}
#'   \item{Gender}{character; as in [motor_portfolio].}
#'   \item{Num_Claims}{integer; sum of `dataCar$numclaims` in segment.}
#'   \item{Total_Incurred}{numeric; aggregated `claimcst0`, scaled by
#'     company loss-multiplier.}
#'   \item{DY0..DY15}{numeric; cumulative paid by development year *k*,
#'     equal to `Total_Incurred × MW2014_proportion(k)`.}
#'   \item{Latest}{numeric; latest cumulative paid (= `DY15` in this synth).}
#'   \item{Reporting_Threshold}{numeric; constant 1,000,000 — used by the
#'     example's "large claims" filter.}
#' }
#'
#' @source Wüthrich, M. V. and Merz, M. (2014). *Stochastic Claims Reserving
#'   Manual: Advances in Dynamic Modeling*. Underlying triangle via the
#'   [ChainLadder](https://cran.r-project.org/package=ChainLadder) package
#'   (`MW2014`).
#'
#' @seealso [motor_portfolio] for the matching premium cube.
#' @keywords datasets
"motor_losses"


#' Property locations — minimal pricing-engine input
#'
#' Twenty insured locations, used as the `locations` input table to
#' [engine_property()] in the property pricing example. Synthetic and
#' deterministic; built by `data-raw/build_property.R` with `set.seed(1)`.
#'
#' @format A data frame with 20 rows and 8 columns:
#' \describe{
#'   \item{location_id}{character; `LOC001`..`LOC020`.}
#'   \item{country}{character; one of Italy / Spain / United Kingdom /
#'     France / Germany.}
#'   \item{peril}{character; `fire` / `flood` / `theft`. The covered peril
#'     for the location — used as a crossfilter dimension in
#'     `portfolio-explorer.R` but otherwise carried through the engine
#'     unchanged.}
#'   \item{postcode}{integer.}
#'   \item{tiv}{numeric; total insured value.}
#'   \item{sra_adj}{numeric; site risk adjustment, around 1.}
#'   \item{deductible}{numeric; per-loss deductible.}
#'   \item{limit}{numeric; per-loss limit.}
#' }
#'
#' @seealso [property_claims], [property_params], [engine_property()].
#' @keywords datasets
"property_locations"


#' Property claims — minimal pricing-engine input
#'
#' Fifteen historical claims spanning 2020–2024, used as the `claims` input
#' table to [engine_property()]. Synthetic; built by
#' `data-raw/build_property.R` with `set.seed(1)`.
#'
#' @format A data frame with 15 rows and 5 columns:
#' \describe{
#'   \item{claim_id}{character; `CL0001`..`CL0015`.}
#'   \item{date_of_loss}{Date.}
#'   \item{country}{character; loss country.}
#'   \item{paid}{numeric; paid amount.}
#'   \item{outstanding}{numeric; case reserve.}
#' }
#'
#' @seealso [property_locations], [property_params], [engine_property()].
#' @keywords datasets
"property_claims"


#' Property pricing parameters — defaults for `engine_property()`
#'
#' Named list of three parameter tables consumed by [engine_property()].
#' Built by `data-raw/build_property.R`.
#'
#' @format A list with three data frames:
#' \describe{
#'   \item{country_factor}{`country` x `country_factor`; multiplicative
#'     adjustment per country.}
#'   \item{base_rate}{`country` x `base_rate`; per-country base rate
#'     (premium per unit of TIV).}
#'   \item{expenses}{`producing_country` x `expenses_factor`; expense
#'     loading applied to risk premium.}
#' }
#'
#' @seealso [property_locations], [property_claims], [engine_property()],
#'   [property_params_comparison].
#' @keywords datasets
"property_params"


#' Property pricing parameters — alternative scenario for the explorer demo
#'
#' Same shape as [property_params], with the Italian `base_rate` bumped by
#' 30%. This is the second parameter set the bundled
#' `inst/examples/portfolio-explorer.R` runs the property portfolio against,
#' so the resulting per-location diff is non-zero (and concentrated in
#' Italian locations). Built by `data-raw/build_property.R`.
#'
#' @format A list with the same three data frames as [property_params].
#'
#' @seealso [property_params], [engine_property()].
#' @keywords datasets
"property_params_comparison"
